name: interface_stone_smart_flutter
description: Pacote de inteface para integrar com o plugin StoneSmartFlutter e facilitar o uso de forma geral com as funçoes de pagamento.
version: 1.0.4
repository: https://github.com/jhonathanqz/stone_smart_flutter

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
