name: stone_smart_flutter
description: Plugin Flutter para integrar sua aplicação com o SDK Android da Stone para meios de pagamento.
version: 1.2.2+2
repository: https://github.com/jhonathanqz/stone_smart_flutter

environment:
  sdk: ">=2.18.5 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  interface_stone_smart_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.qztech.stone_smart_flutter
        pluginClass: StoneSmartFlutterPlugin
