on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Set up Flutter SDK path
        run: echo "/flutter/bin" >> $GITHUB_PATH

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk
          wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          unzip sdk-tools-linux-4333796.zip -d $HOME/android-sdk
          echo "sdk.dir=$HOME/android-sdk" > local.properties
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/tools/bin
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-30" "build-tools;30.0.3"

      - name: Install dependencies for stone_smart_flutter
        run: flutter pub get
        working-directory: stone_smart_flutter

      - name: Format code for stone_smart_flutter
        run: dart format --fix .
        working-directory: stone_smart_flutter

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config

      - name: Publish stone_smart_flutter
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          skipTests: true
        env:
          PROJECT_DIR: stone_smart_flutter
