on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      # Stone Smart Flutter
      - name: Set up stone_smart_flutter directory
        run: cd stone_smart_flutter
        shell: bash

      - name: Install dependencies for stone_smart_flutter
        run: flutter pub get
        working-directory: stone_smart_flutter

      - name: Format code for stone_smart_flutter
        run: dart format --fix .
        working-directory: stone_smart_flutter

      - name: Publish stone_smart_flutter
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          skipTests: true
        env:
          PROJECT_DIR: stone_smart_flutter
