on:
  release:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      # Interface Stone Smart Flutter
      - name: Install dependencies for interface_stone_smart_flutter
        run: |
          cd interface_stone_smart_flutter
          flutter pub get

      - name: Format code for interface_stone_smart_flutter
        run: |
          cd interface_stone_smart_flutter
          dart format --fix .

      - name: Publish interface_stone_smart_flutter
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
        env:
          PROJECT_DIR: interface_stone_smart_flutter
